### ISSUE TITLE
Missing .gitignore file

### ISSUE THREAD

**Issue by kabourneeak** [terrybuck/Evilution#20]
There are a lot of private and/or compiled artifacts in this repository;   The GitHub .gitignore project has a starter file for visual studio projects [here](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore).

Git does not ignore files that are already being tracked, so you will need to `git rm` files to remove them from the index to get them to start being ignored again.

**Comment by terrybuck** [comment]
Thanks, that makes a lot of sense and explains why I need to close vs to get everything committed so I can change branches.

**Comment by terrybuck** [comment]
I believe I have removed all the unwanted files and the .gitignore appears to be working

**Comment by kabourneeak** [comment]
Remove `EvilEvolved_TemporaryKey.pfx` as well.

**Comment by terrybuck** [comment]
Thanks, got it.
