### ISSUE TITLE
Overly verbose code in AudioManager

### ISSUE THREAD

**Issue by andrewanderson** [terrybuck/Evilution#33]
https://github.com/terrybuck/Evilution/blob/d9c256c202a1a5f60a6fa1b8afed8de6246d8493/EvilEvolved/EvilEvolved/AudioManager.cs#L42-L47

This could be a single return statement, instead of an if-structure.

**Comment by terrybuck** [comment]
True, their is a couple places I have done this, I will change them all to a simple:

```c#
return (size_before_add < size_after_add);
```

**Comment by terrybuck** [comment]
closed with commit 66f8d829157717808b73fcff36275f612d75555b
